// Blog content. Each post has metadata + a `body` made of simple blocks that
// the BlogPost page renders. To add a post, copy one object and edit it.
// Block types: 'p' (paragraph), 'h2', 'h3', 'ul'/'ol' (items[]), 'callout', 'quote'.

export const posts = [
  {
    slug: 'first-dwc-bucket-weekend-build',
    title: 'Your First DWC Bucket: A Weekend Build',
    tag: 'Beginner',
    excerpt: 'The cheapest, most forgiving way to start growing hydroponically — start to finish in a single weekend.',
    readTime: '6 min',
    date: 'Jul 12, 2026',
    author: 'Elevated Masses',
    body: [
      { type: 'p', text: 'Deep Water Culture (DWC) is where almost every indoor grower should start. There are no pumps to clog, no timers to program, and no drippers to unclog at 2 a.m. Your plant sits with its roots dangling in oxygen-rich, nutrient-filled water, and it grows fast. This is a build you can finish over a weekend with parts from any hardware store.' },
      { type: 'h2', text: 'What you\'ll need' },
      { type: 'ul', items: [
        'A 5-gallon bucket with a lid (opaque — light in the reservoir grows algae)',
        'A 6-inch net pot that fits a hole cut in the lid',
        'An air pump, air stone, and airline tubing',
        'Clay pebbles (hydroton) to hold the net pot',
        'A starter plug or rockwool cube with your seedling',
        'pH test kit and a basic nutrient solution',
      ] },
      { type: 'callout', text: 'Total cost is usually $30–$50 for your first bucket, and most of that (the pump and meters) you reuse forever.' },
      { type: 'h2', text: 'The build, step by step' },
      { type: 'ol', items: [
        'Cut a hole in the bucket lid so the net pot sits snugly with its lip resting on top.',
        'Drill a small hole near the top edge of the bucket for the airline, so you can seal the lid without pinching the tube.',
        'Drop the air stone in the bottom, connect it to the pump, and run the line out through that hole.',
        'Fill the bucket with water until it will just touch the bottom of the net pot — about an inch of contact.',
        'Add nutrients per the label, then check and adjust pH to 5.5–6.5.',
        'Nestle your seedling plug into the net pot and surround it with clay pebbles.',
        'Turn on the air pump and leave it running 24/7.',
      ] },
      { type: 'h2', text: 'The first two weeks' },
      { type: 'p', text: 'Early on, the roots are short and rely on that inch of water contact and the humidity in the bucket. As roots reach down into the reservoir, you can actually lower the water level slightly — roots love the oxygen-rich air gap between the lid and the water line. Top up with pH-balanced water as the level drops.' },
      { type: 'p', text: 'Check pH every couple of days. It will drift as the plant drinks, and drift is the number-one cause of the deficiencies beginners panic about. Keep it in range and most problems never start.' },
      { type: 'callout', text: 'Warm water holds less oxygen and breeds root rot. Keep your reservoir below about 68°F (20°C) — a frozen water bottle floated in the bucket on hot days works in a pinch.' },
      { type: 'h2', text: 'What good looks like' },
      { type: 'p', text: 'Within a week you should see new growth. Within two, roots should be visibly reaching into the water and turning bright white. White, stringy roots mean a happy plant. Brown, slimy, or smelly roots mean low oxygen or warm water — fix the temperature and airflow first, before you reach for any bottle of nutrients.' },
      { type: 'p', text: 'That\'s it. One bucket, one weekend, and you\'ve got a working hydroponic system you fully understand. Once it clicks, scaling up to multiple buckets or a recirculating system is just more of the same idea.' },
    ],
  },
  {
    slug: 'reading-nutrient-deficiencies-leaf-color',
    title: 'Reading Nutrient Deficiencies by Leaf Color',
    tag: 'Troubleshooting',
    excerpt: 'A visual guide to what yellowing, spotting, and curling are really telling you — and how to respond.',
    readTime: '9 min',
    date: 'Jul 12, 2026',
    author: 'Elevated Masses',
    body: [
      { type: 'p', text: 'Your plant talks to you through its leaves. The trick is learning to read the two most important clues: which leaves are affected (old bottom growth vs. new top growth), and what the damage actually looks like. Those two questions narrow almost every problem down fast.' },
      { type: 'h2', text: 'First, check pH — not your nutrients' },
      { type: 'callout', text: 'Most "deficiencies" in hydroponics are actually lockout: the nutrient is in the water, but the wrong pH stops the roots from absorbing it. Before adding anything, confirm your pH is 5.5–6.5.' },
      { type: 'p', text: 'If you skip this step you\'ll chase symptoms in circles, dumping in more of a nutrient the plant literally cannot take up. Fix pH, wait a few days, and watch new growth before you diagnose further.' },
      { type: 'h2', text: 'Old leaves vs. new leaves' },
      { type: 'p', text: 'Some nutrients are "mobile" — the plant can move them from old leaves to new growth when it runs short. Those deficiencies show up on the bottom, older leaves first. Others are "immobile" and show up on the new top growth first. This single distinction is the most useful diagnostic tool you have.' },
      { type: 'h3', text: 'Shows up on OLD/lower leaves first' },
      { type: 'ul', items: [
        'Nitrogen: uniform pale-green to yellow, starting from the tips and moving in; whole lower leaves fade evenly.',
        'Magnesium: yellowing between the veins while the veins stay green (interveinal), often with rusty spots.',
        'Potassium: yellowing and brown, crispy edges and tips on lower leaves.',
      ] },
      { type: 'h3', text: 'Shows up on NEW/upper leaves first' },
      { type: 'ul', items: [
        'Calcium: new growth is distorted, spotted, or has brown necrotic patches; tips may hook.',
        'Iron: bright yellow new leaves with sharp green veins (a vivid interveinal contrast).',
        'Sulfur: pale, uniformly yellow new growth (looks like nitrogen but on the top instead of the bottom).',
      ] },
      { type: 'callout', text: 'Nitrogen = bottom, uniform, fading up. Iron = top, bright yellow with green veins. Those two cover a huge share of what beginners see.' },
      { type: 'h2', text: 'It might not be a deficiency at all' },
      { type: 'p', text: 'Overwatering-style root problems, light burn, and heat stress all mimic deficiencies. Light burn bleaches the leaves closest to the lamp. Heat stress curls edges upward like tacos. Root rot causes sudden droop despite plenty of water. Rule these out before you adjust your feed.' },
      { type: 'h2', text: 'A calm troubleshooting order' },
      { type: 'ol', items: [
        'Check and correct pH first.',
        'Note whether the damage is on old or new growth.',
        'Match the pattern (uniform, interveinal, edges, spots) to the list above.',
        'Change one thing at a time, then wait 3–5 days.',
        'Judge success by NEW growth — damaged old leaves rarely recover, and that\'s normal.',
      ] },
      { type: 'p', text: 'Snap a photo before and after each change. Over a few grows you\'ll build a personal reference that beats any chart — and if you\'re stuck, that\'s exactly what our Plant AI and the forum are for.' },
    ],
  },
  {
    slug: 'led-grow-lights-specs-explained',
    title: 'LED Grow Lights: What the Specs Actually Mean',
    tag: 'Gear',
    excerpt: 'PPFD, PAR, efficacy, wattage — cut through the marketing and buy the right light for your space.',
    readTime: '7 min',
    date: 'Jul 12, 2026',
    author: 'Elevated Masses',
    body: [
      { type: 'p', text: 'Grow-light listings are a swamp of numbers, and the biggest one — "1000W!" — is usually the most misleading. Here\'s what each spec really means and which ones actually decide whether your plants thrive.' },
      { type: 'h2', text: 'Ignore "equivalent" wattage' },
      { type: 'callout', text: 'A light advertised as "1000W" that actually draws 100W from the wall is a 100W light. Look for the ACTUAL power draw, usually in the fine print or specs table.' },
      { type: 'p', text: 'Real wattage matters for two reasons: your electricity bill, and a rough sanity check on output. But wattage alone tells you nothing about how much usable light reaches your plants. For that, you need PAR and PPFD.' },
      { type: 'h2', text: 'PAR, PPFD, and DLI — the ones that matter' },
      { type: 'ul', items: [
        'PAR is the slice of light (roughly 400–700nm) that plants use for photosynthesis. It\'s a range, not a single number.',
        'PPFD measures how much of that light actually lands on a spot, in micromoles per second per square meter (µmol/m²/s). This is the number that matters — but only at a stated distance and coverage area.',
        'DLI is PPFD added up over a full day. It\'s the truest measure of how much light your plant received.',
      ] },
      { type: 'callout', text: 'A PPFD number with no distance and no coverage area is marketing, not data. "1500 PPFD" directly under the lens means nothing if it\'s 200 at the corners of your tent.' },
      { type: 'h2', text: 'Efficacy: light per watt' },
      { type: 'p', text: 'Efficacy (µmol/J) tells you how efficiently a fixture turns electricity into usable light. Modern quality LEDs land around 2.5–3.0 µmol/J. Higher means more light and less heat for the same power bill. If a listing hides this number, that\'s often a sign it isn\'t flattering.' },
      { type: 'h2', text: 'Rough targets by stage' },
      { type: 'ul', items: [
        'Seedlings & clones: ~200–400 PPFD — gentle, they burn easily.',
        'Vegetative growth: ~400–600 PPFD.',
        'Flowering/fruiting: ~600–900 PPFD (add CO₂ before pushing higher).',
      ] },
      { type: 'h2', text: 'How to actually choose' },
      { type: 'ol', items: [
        'Start from your space: measure your grow area in square feet.',
        'Pick a light rated to cover that area at flowering PPFD, at a realistic hanging height.',
        'Check the real wattage and efficacy — favor 2.5+ µmol/J from a brand that publishes a PPFD map.',
        'Buy a little more coverage than you think you need; dimming down is easy, adding light later is not.',
      ] },
      { type: 'p', text: 'A $30 PAR meter (or a phone app in a pinch) takes the guesswork out entirely. Measure at canopy height across your whole footprint, and adjust hanging height until the numbers match the stage you\'re in.' },
    ],
  },
  {
    slug: 'mixing-your-first-nutrient-reservoir',
    title: 'Mixing Your First Nutrient Reservoir: pH, EC & Order of Operations',
    tag: 'Nutrients',
    excerpt: 'EC, pH, and the order you add things — a repeatable recipe for healthy roots and no nasty surprises.',
    readTime: '8 min',
    date: 'Jul 12, 2026',
    author: 'Elevated Masses',
    body: [
      { type: 'p', text: 'Mixing nutrients feels intimidating until you\'ve done it twice. It\'s really just a recipe, and the order matters more than most beginners realize. Follow the same steps every time and your reservoir becomes boringly reliable — which is exactly what you want.' },
      { type: 'h2', text: 'The two numbers you\'re managing' },
      { type: 'ul', items: [
        'EC (electrical conductivity) tells you how strong your nutrient solution is — how much food is dissolved in the water. Some meters show this as PPM.',
        'pH tells you how acidic or alkaline the water is, which controls whether roots can actually absorb that food.',
      ] },
      { type: 'callout', text: 'Target ranges for most hydroponic crops: EC around 1.2–2.0 (roughly 600–1000 PPM) depending on stage, and pH 5.5–6.5.' },
      { type: 'h2', text: 'Start with the right water' },
      { type: 'p', text: 'Test your tap water\'s EC before you add anything. Hard tap water can start at 0.3–0.5 EC, which eats into your budget and can carry excess calcium or magnesium. If your starting water is very hard, many growers switch to filtered or RO water so they control exactly what goes in.' },
      { type: 'h2', text: 'The order of operations' },
      { type: 'ol', items: [
        'Start with your reservoir full of plain water at room temperature.',
        'If you use a Cal-Mag supplement, add it first and stir.',
        'Add nutrients one bottle at a time, stirring between each — never pour concentrates together, or they can bind into a solid your plant can\'t use.',
        'Stir well and let it mix for a minute.',
        'Now measure EC. Adjust with more nutrient (stronger) or more water (weaker) to hit your target.',
        'Only after EC is set, measure and adjust pH.',
      ] },
      { type: 'callout', text: 'Always set EC before pH. Adding nutrients changes pH, so there\'s no point dialing in pH first — you\'d just have to redo it.' },
      { type: 'h2', text: 'Adjusting pH safely' },
      { type: 'p', text: 'Use dedicated "pH Down" (usually phosphoric acid) or "pH Up" in tiny amounts — a little goes a long way. Add a few drops, stir, wait, then re-measure. Overshooting and bouncing back and forth stresses the solution and wastes product. Patience here saves you headaches.' },
      { type: 'h2', text: 'Keeping it stable' },
      { type: 'ul', items: [
        'Check pH every day or two — it drifts as the plant feeds.',
        'Top up with plain pH-balanced water as the level drops; the plant drinks water faster than it eats nutrients, so straight top-ups keep EC from creeping up.',
        'Do a full reservoir change every 1–2 weeks to reset any imbalance you can\'t see.',
      ] },
      { type: 'p', text: 'Write your recipe down — starting water EC, how much of each bottle, final EC and pH. After a few reservoirs you\'ll have a repeatable formula dialed to your water and your plants, and mixing day becomes a five-minute habit instead of a guessing game.' },
    ],
  },
]

export function getPost(slug) {
  return posts.find((p) => p.slug === slug)
}
