import { PageHeader, StubNote } from '../components/ui.jsx'
import { Upload, ScanLine, Sparkles, ShieldCheck, ArrowRight, ExternalLink } from 'lucide-react'

const DIAGNOSTIC_TOOL_URL = 'https://theplantdiagnosticstool.com'

export default function PlantAI() {
  return (
    <>
      <PageHeader
        eyebrow="Plant AI · Powered by The, Plant Diagnostic Tool, Period."
        title="Diagnose a plant problem"
        description="Upload a photo, describe the symptoms, and get likely causes and fixes in seconds. Plant AI now runs on its own dedicated tool for a faster, better experience."
      >
        <a href={`${DIAGNOSTIC_TOOL_URL}/tool`} target="_blank" rel="noopener noreferrer" className="btn-primary">
          Diagnose a plant <ArrowRight size={16} />
        </a>
      </PageHeader>

      <div className="container-em py-12">
        <StubNote>
          Diagnoses are generated by AI from your photo and description — genuinely useful as a first read,
          but not a substitute for experience. Always keep monitoring your plant.
        </StubNote>

        <div className="mt-10 grid gap-8 lg:grid-cols-[1fr_1fr] lg:items-center">
          <div>
            <span className="eyebrow">How it works</span>
            <h2 className="mt-3 text-2xl font-700 text-fg">Same diagnosis, a dedicated home</h2>
            <ul className="mt-6 space-y-4">
              {[
                { icon: Upload, t: 'You submit', d: 'A photo and a quick description of the symptoms.' },
                { icon: Sparkles, t: 'You get answers', d: 'Likely causes and concrete fixes in seconds.' },
                { icon: ShieldCheck, t: 'Free to start', d: 'A free account gets you a weekly allotment of diagnoses — no card required.' },
              ].map(({ icon: Icon, t, d }) => (
                <li key={t} className="flex gap-3">
                  <span className="inline-flex h-10 w-10 shrink-0 items-center justify-center rounded-xl bg-green/10 text-green"><Icon size={18} /></span>
                  <span><span className="block font-600 text-fg">{t}</span><span className="block text-sm text-muted">{d}</span></span>
                </li>
              ))}
            </ul>
            <a
              href={`${DIAGNOSTIC_TOOL_URL}/tool`}
              target="_blank"
              rel="noopener noreferrer"
              className="btn-primary mt-8"
            >
              Try it now <ArrowRight size={16} />
            </a>
          </div>

          <div className="card flex flex-col items-center justify-center p-10 text-center">
            <span className="flex h-16 w-16 items-center justify-center rounded-2xl bg-purple/10 text-purple-soft">
              <ScanLine size={30} />
            </span>
            <h3 className="mt-4 text-lg font-600 text-fg">The, Plant Diagnostic Tool, Period.</h3>
            <p className="mt-2 max-w-xs text-sm text-muted">
              A free-to-start plant diagnosis tool for any plant — vegetables, herbs, houseplants, and more.
            </p>
            <a
              href={DIAGNOSTIC_TOOL_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="btn-ghost mt-6"
            >
              Visit theplantdiagnosticstool.com <ExternalLink size={15} />
            </a>
          </div>
        </div>
      </div>
    </>
  )
}
